# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('psk', models.CharField(max_length=128, unique=True)),
                ('last_check_date', models.DateField()),
            ],
        ),
    ]
