# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_check_date',
            field=models.DateField(null=True),
        ),
    ]
