# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170128_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='last_check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
