ipcatcher:
  restart: always
  build: ./ipcatcher/
  expose:
    - "8080"
  volumes:
    - ./ipcatcher:/usr/src/app
    - ./data:/data
  command: /usr/local/bin/gunicorn -w 2 -b 127.0.0.1:8000 ipcatcher:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - ipcatcher
  links:
    - ipcatcher:ipcatcher
