version: "3"

services:
  ipcatcher:
    restart: always
    build: ./ipcatcher/
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 ipcatcher.wsgi

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - ipcatcher:ipcatcher

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
