version: "3"

services:
  ipcatcher:
    restart: always
    build: ./ipcatcher/
    expose:
      - "8000"
    volumes:
      - ./ipcatcher:/usr/src/app
      - ./data:/data
    command: /usr/local/bin/gunicorn -w 2 -b 127.0.0.1:8000 ipcatcher:app

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - ipcatcher:ipcatcher
